In [1]:
%reset
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import numpy as np
from time import time

from process_network import processNetwork
%matplotlib inline

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [60]:
x = np.array([1,2,3,4,5,6,7,8,9])
data = np.tile(x[np.newaxis,:], [5,1])
i, j1, j2 = 3, 4, 0
lag1, lag2 = -1, 3

In [61]:
def getTargetSourceData(data, i, j1, j2, lag1, lag2):
    '''
    Get the data for the target variable and the two source variables with
    time lag.
    Inputs:
        i          -- the index of the target variable [int]
        j1, j2     -- the indices of the two source variables [int]
        lag1, lag2 -- the time lags of the two source variables [int]
    Outputs:
        dtar       -- the array of the target variable [ndarray]
        ds1        -- the array of the source variable 1 [ndarray]
        ds2        -- the array of the source variable 2 [ndarray]
    '''
    dtar, ds1, ds2 = data[:, i], data[:, j1], data[:, j2]
    print dtar, ds1, ds2

    # Adjust the three variables according to the source 1
    if lag1 > 0:   # the source 1 is delayed
        dtar = dtar[:-lag1]
        ds2 = ds2[:-lag1]
        ds1 = ds1[lag1:]
    elif lag1 < 0:  # the source 1 is forwarded
        lag1 = -lag1
        dtar = dtar[lag1:]
        ds2 = ds2[lag1:]
        ds1 = ds1[:-lag1]
    elif lag1 == 0:  # no delay
        dtar = dtar
        dtar = dtar
        ds1 = ds1
    print dtar, ds1, ds2
        
    # Adjust the three variables according to the source 2
    if lag2 > 0:   # the source 1 is delayed
        dtar = dtar[:-lag2]
        ds1 = ds1[:-lag2]
        ds2 = ds2[lag2:]
    elif lag2 < 0:  # the source 1 is forwarded
        lag2 = -lag2
        dtar = dtar[lag2:]
        ds1 = ds1[lag2:]
        ds2 = ds2[:-lag2]
    elif lag2 == 0:  # no delay
        dtar = dtar
        ds2 = ds2
        ds1 = ds1
    
    return dtar, ds1, ds2
    
getTargetSourceData(data.T, i, j1, j2, lag1, lag2)

[1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8] [2 3 4 5 6 7 8 9]


(array([2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5]), array([5, 6, 7, 8, 9]))

In [62]:
def getTargetSourceData2(data, i, j1, j2, lag1, lag2):
    '''
    Get the data for the target variable and the two source variables with
    time lag.
    Inputs:
        i          -- the index of the target variable [int]
        j1, j2     -- the indices of the two source variables [int]
        lag1, lag2 -- the time lags of the two source variables [int]
    Outputs:
        dtar       -- the array of the target variable [ndarray]
        ds1        -- the array of the source variable 1 [ndarray]
        ds2        -- the array of the source variable 2 [ndarray]
    '''
    dtar, ds1, ds2 = data[:, i], data[:, j1], data[:, j2]

    # Readjust ds1 and ds2 based on the their lags
    ds1 = ds1[lag1:] if lag1 > 0 else ds1[:lag1] if lag1 < 0 else ds1
    ds2 = ds2[lag2:] if lag2 > 0 else ds2[:lag2] if lag2 < 0 else ds2
    print ds1, ds2

    # Get the minimum length of the array
    minlen = np.min([dtar.size, ds1.size, ds2.size])
    print minlen

    # Now each data set starts from the defined time.
    # Therefore, cut the tail part tha exceeds minlen.
    dtar, ds1, ds2 = dtar[:minlen], ds1[:minlen], ds2[:minlen]

    return dtar, ds1, ds2

getTargetSourceData2(data.T, i, j1, j2, lag1, lag2)

[1 2 3 4 5 6 7 8] [4 5 6 7 8 9]
6


(array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4, 5, 6]),
 array([4, 5, 6, 7, 8, 9]))

In [2]:
N=100000
a_set = np.zeros(N)
b_set = np.ones(N)

print 'Test 1...'
start = time()
for a in a_set:
    a**2
print time()-start

start = time()
for a in np.nditer(a_set):
    a**2
print time()-start

print 'Test 2...'
start = time()
for i in range(N):
    b_set[i] = a_set[i]**2
print time()-start

start = time()
b_set = np.array(map(lambda i: a_set[i]**2, range(N)))
print time()-start

start = time()
b_set = np.array(map(lambda a: a**2, a_set))
print time()-start

Test 1...
0.0488939285278
0.103842020035
Test 2...
0.047308921814
0.0533618927002
0.0441288948059
